services:
  - type: web
    name: kudiway-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn kudiway_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
